from typing import List
from openai import OpenAI
import os
from dotenv import load_dotenv
import ast
from agents import research_agent, writer_agent, editor_agent

load_dotenv()

client = OpenAI(
  base_url = "https://integrate.api.nvidia.com/v1",
  api_key = os.getenv("NVIDIA_API_KEY"),
)

def convert_string_to_list(s: str) -> list:
    """
    A function to convert a list contained within a string to a list object in python.

    Arguments:
        s (str): the string from which the list has to be extracted.

    Returns:
        obj (list): The list extracted from the string
    """
    try:
        obj = ast.literal_eval(s.strip())
        if isinstance(obj, list) and all(isinstance(x, str) for x in obj):
            return obj
    except Exception:
        pass
    return []

def planner_agent(topic: str, model: str="nvidia/nemotron-3-ultra-550b-a55b") -> List[str]:
    """
    A function to carry out a step for the research_agent in the agentic workflow.

    Arguments:
        prompt (str): The text input by the user on which the research has to be carried out.
        model (str): The LLM to be used to carry out the tasks.

    Returns:
        lst_commands (list): A list of ordered commands for the execution of different agents in the agentic workflow.
    """

    prompt = f"""
    You are a planning agent responsible for organizing a research workflow using multiple intelligent agents.

    Available agents:
    - Research agent: Will perform deep research from various sources and collate all the results. It has access to the following tools:
        -- arxiv search tool -> to search for academic papers on arxiv
        -- tavily search tool -> to perform a broad web search using tavily
        -- wikipedia search tool -> **(if needed)** to get wikipedia information about the topic
        -- semantic scholar search tool -> **(if needed)** to get results on papers from semantic scholar if arxiv does not have enough content on the topic
        -- web scrape from urls tool -> **(if needed)** to web scrape the contents from the links of the pages collated from the arxiv, tavily, wikipedia and semantic scholar searches
        -- run python code tool -> **(if needed)** provides an environment to run any python code that the model may generate if it wants to run a simulation/test hypothesis, etc. 
    - Writer agent: Will draft a strong academic report based on the research resources collated.
    - Editor agent: Will refine the report draft and improve it for clarity, cohesiveness and will proofread it as well. Will reflect on the contents of the report and check for proper citations/sources.

    YOUR TASK IS: Produce a step-by-step plan **as a valid list of Python strings** (no markdown, no explanations).
    Each step must be atomic, actionable and assigned to one of the agents mentioned above.
    There can be a maximum of 7 steps.

    DO NOT INCLUDE STEPS LIKE "create CSV", "set up repo", "install packages", etc.
    FOCUS on meaningful research tasks (search, extract, rank, draft, revise).

    THE FIRST STEP MUST BE EXACTLY (with the topic added into the prompt you):
    "Research agent: Perform an arxiv search on the topic given and collect all the relevant information (title, summary, published, authors, url)"

    THE SECOND STEP MUST BE EXACTLY (with the topic added into the prompt you):
    "Research agent: After the arxiv search step, perform a broad tavily search and collate all information from there."

    THE THIRD STEP MUST BE EXACTLY (with the topic added into the prompt you):
    "Research agent: Review the arxiv and tavily results gathered so far. Based on what is actually missing or insufficient, decide whether to additionally use the semantic scholar tool, wikipedia tool, webscrape tool, and/or run python code tool. Do not use a tool unless the gathered material shows a real need for it."

    The SECOND TO LAST STEP must instruct the writer agent to generate a comprehensive markdown report that:
    - Uses all findings and outputs from previous steps
    - Includes inline citations (e.g., [1], (Wikipedia/arXiv))
    - Includes a References section with clickable links for all citations
    - Preserves earlier sources
    - Is detailed and self-contained

    THE FINAL STEP must instruct the editor agent to proofread the report generated by the writer agent. While proofreading the editor agent needs to note:
    - All the places where there is an inconsistent/incorrect citation.
    - All fixes that need to be made to improve cohesiveness and clarity.
    - Any content that needs to be elaborated upon.
    - If there are no fixes/changes to be made anywhere in the report, the editor can return the report back to the user.

    Make sure all steps contain a mention of the topic that is to be researched on. This is **MANDATORY**.

    Do not produce separate steps that individually pre-assign the semantic scholar, wikipedia, or code execution tools — the research agent decides at execution time, based on what the arxiv and tavily results actually show, not in advance. 
    Use cases the research agent should apply when making that call:
    Semantic scholar tool -> Should likely be called when arxiv may not generate quality results on topics other than math/cs/econ/quant, etc.
    Wikipedia tool -> should likely be called when there is a lack of basic information about the topic available from other sources.
    Run python code tool -> should only be called if the research agent feels like it needs to test something out with code.

    Topic: {topic}
    """

    response = client.chat.completions.create(
        model=model,
        messages = [{"role": "user", "content": prompt}],
        temperature=1
    )

    raw = response.choices[0].message.content.strip()
    lst_commands = convert_string_to_list(raw)

    return lst_commands

def executor_agent(step_title: str, history: list, prompt: str, step_index: int, source_context: str = ""):
    """
    Executes a step of the executor agent.

    Arguments:
    step_title (str): The title of the current step to be performed.
    history (list): A log of all the commands that have been performed. Contains information about the agent and the description of the task it performed.
    prompt (str): The tasks the model has to execute in the current step.
    step_index (int): The sequential index of the step that has to be performed in the workflow.
    source_context (str): A formatted string of all the sources that have been accessed during the research phase of the agentic workflow.

    Returns:
    step_title (str): The title of the current step to be performed.
    agent_name (str): The agent which has been called
    content (str): The output produced by the agent call.
    sources (str): A formatted string of all the sources that have been accessed during the research phase of the agentic workflow.
    """

    # creating a context string using the history to provide to the agent
    context = f"User Prompt:\n{prompt}\n\nHistory so far:\n"
    for i, (desc, agent, output) in enumerate(history):
        if "draft" in desc.lower() or agent == "writer_agent":
            context += f"\nDraft (Step {i + 1}):\n{output.strip()}\n"
        elif "feedback" in desc.lower() or agent == "editor_agent":
            context += f"\nFeedback (Step {i + 1}):\n{output.strip()}\n"
        elif "research" in desc.lower() or agent == "research_agent":
            context += f"\nResearch (Step {i + 1}):\n{output.strip()}\n"
        else:
            context += f"\nOther (Step {i + 1}):\n{output.strip()}\n"

    # adding the context to the task to pass onto the agent
    task_with_context = f"""{context}

    Your next task:
    {step_title}
    """

    # Selection of agent based on the task
    if step_index == 0:
        content, messages, sources = research_agent(task_with_context, allowed_tools=["arxiv_search_tool"], max_turns=5)
        agent_name = "research_agent"
    elif step_index == 1:
        content, messages, sources = research_agent(task_with_context, allowed_tools=["tavily_search_tool"], max_turns=5)
        agent_name = "research_agent"
    elif step_index == 2:
        content, messages, sources = research_agent(task_with_context, allowed_tools=None, max_turns=8)
        agent_name = "research_agent"
    elif "draft" in step_title.lower() or "writer" in step_title.lower():
        content, messages, sources = writer_agent(task_with_context, source_context=source_context)
        agent_name = "writer_agent"
    elif "revise" in step_title.lower() or "editor" in step_title.lower() or "proofread" in step_title.lower():
        content, messages, sources = editor_agent(task_with_context)
        agent_name = "editor_agent"
    else:
        raise ValueError(f"Unknown step type: {step_title}")

    print(f"{agent_name} Output: ", content)
    return step_title, agent_name, content, sources
    

